// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework;

namespace Mosa.Compiler.x86.Transforms.Tweak;

[Transform("x86.Temp")]
public sealed class Lea32ToLea32v2 : BaseTransform
{
	public Lea32ToLea32v2() : base(X86.Lea32, TransformType.Manual | TransformType.Optimization)
	{
	}

	public override bool Match(Context context, Transform transform)
	{
		return true;
	}

	public override void Transform(Context context, Transform transform)
	{
		var result = context.Result;
		var operand1 = context.Operand1;
		var operand2 = context.Operand2;

		if (operand2.IsConstant)
		{
			context.SetInstruction(X86.Lea32Ext, result, operand1, Operand.Constant32_0, Operand.Constant32_1, operand2);
		}
		else
		{
			context.SetInstruction(X86.Lea32Ext, result, operand1, operand2, Operand.Constant32_1, Operand.Constant32_0);
		}
	}
}
