// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// AddCarryIn32
/// </summary>
public sealed class AddCarryIn32 : BaseIRInstruction
{
	public AddCarryIn32()
		: base(3, 1)
	{
	}
}
