// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// ArithShiftRight32
/// </summary>
public sealed class ArithShiftRight32 : BaseIRInstruction
{
	public ArithShiftRight32()
		: base(2, 1)
	{
	}
}
