// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// BitCopyR8To64
/// </summary>
public sealed class BitCopyR8To64 : BaseIRInstruction
{
	public BitCopyR8To64()
		: base(1, 1)
	{
	}
}
