// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// BranchManagedPointer
/// </summary>
public sealed class BranchManagedPointer : BaseIRInstruction
{
	public BranchManagedPointer()
		: base(0, 2)
	{
	}

	public override bool IsFlowNext => false;

	public override bool IsConditionalBranch => true;

	public override bool IsBranch => true;
}
