// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// CheckedConversionU64ToI32
/// </summary>
public sealed class CheckedConversionU64ToI32 : BaseIRInstruction
{
	public CheckedConversionU64ToI32()
		: base(1, 1)
	{
	}
}
