// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// CheckArrayBounds
/// </summary>
public sealed class CheckArrayBounds : BaseIRInstruction
{
	public CheckArrayBounds()
		: base(0, 2)
	{
	}
}
