// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// CheckThrowOverflow
/// </summary>
public sealed class CheckThrowOverflow : BaseIRInstruction
{
	public CheckThrowOverflow()
		: base(1, 0)
	{
	}
}
