// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// ConvertU32ToR8
/// </summary>
public sealed class ConvertU32ToR8 : BaseIRInstruction
{
	public ConvertU32ToR8()
		: base(1, 1)
	{
	}
}
