// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// IfThenElse32
/// </summary>
public sealed class IfThenElse32 : BaseIRInstruction
{
	public IfThenElse32()
		: base(3, 1)
	{
	}
}
