// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// IfThenElse64
/// </summary>
public sealed class IfThenElse64 : BaseIRInstruction
{
	public IfThenElse64()
		: base(3, 1)
	{
	}
}
