// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// IsInstanceOfInterfaceType
/// </summary>
public sealed class IsInstanceOfInterfaceType : BaseIRInstruction
{
	public IsInstanceOfInterfaceType()
		: base(2, 1)
	{
	}

	public override bool IsMemoryRead => true;
}
