// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// Jmp
/// </summary>
public sealed class Jmp : BaseIRInstruction
{
	public Jmp()
		: base(0, 0)
	{
	}

	public override bool IsFlowNext => false;

	public override bool IsUnconditionalBranch => true;
}
