// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// LoadZeroExtend16x64
/// </summary>
public sealed class LoadZeroExtend16x64 : BaseIRInstruction
{
	public LoadZeroExtend16x64()
		: base(2, 1)
	{
	}

	public override bool IsMemoryRead => true;
}
