// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// LoadZeroExtend16x32
/// </summary>
public sealed class LoadZeroExtend16x32 : BaseIRInstruction
{
	public LoadZeroExtend16x32()
		: base(2, 1)
	{
	}

	public override bool IsMemoryRead => true;
}
