// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// MemorySet
/// </summary>
public sealed class MemorySet : BaseIRInstruction
{
	public MemorySet()
		: base(3, 1)
	{
	}
}
