// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// MoveObject
/// </summary>
public sealed class MoveObject : BaseIRInstruction
{
	public MoveObject()
		: base(1, 1)
	{
	}

	public override bool IsMove => true;
}
