// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// MulHs32 - Multiply high signed
/// </summary>
public sealed class MulHs32 : BaseIRInstruction
{
	public MulHs32()
		: base(2, 1)
	{
	}

	public override bool IsCommutative => true;
}
