// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// MulSigned64
/// </summary>
public sealed class MulSigned64 : BaseIRInstruction
{
	public MulSigned64()
		: base(2, 1)
	{
	}

	public override bool IsCommutative => true;
}
