// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// MulUnsigned32
/// </summary>
public sealed class MulUnsigned32 : BaseIRInstruction
{
	public MulUnsigned32()
		: base(2, 1)
	{
	}

	public override bool IsCommutative => true;
}
