// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// Neg64
/// </summary>
public sealed class Neg64 : BaseIRInstruction
{
	public Neg64()
		: base(2, 1)
	{
	}

	public override bool IsCommutative => true;
}
