// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// NewArray
/// </summary>
public sealed class NewArray : BaseIRInstruction
{
	public NewArray()
		: base(2, 1)
	{
	}

	public override bool IsMemoryWrite => true;
}
