// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// Nop
/// </summary>
public sealed class Nop : BaseIRInstruction
{
	public Nop()
		: base(0, 0)
	{
	}
}
