// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// Not32
/// </summary>
public sealed class Not32 : BaseIRInstruction
{
	public Not32()
		: base(1, 1)
	{
	}
}
