// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// ShiftRight32
/// </summary>
public sealed class ShiftRight32 : BaseIRInstruction
{
	public ShiftRight32()
		: base(2, 1)
	{
	}
}
