// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// ShiftLeft64
/// </summary>
public sealed class ShiftLeft64 : BaseIRInstruction
{
	public ShiftLeft64()
		: base(2, 1)
	{
	}
}
