// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// SignExtend8x32
/// </summary>
public sealed class SignExtend8x32 : BaseIRInstruction
{
	public SignExtend8x32()
		: base(1, 1)
	{
	}
}
