// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// SignExtend16x64
/// </summary>
public sealed class SignExtend16x64 : BaseIRInstruction
{
	public SignExtend16x64()
		: base(1, 1)
	{
	}
}
