// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// StoreCompound
/// </summary>
public sealed class StoreCompound : BaseIRInstruction
{
	public StoreCompound()
		: base(3, 0)
	{
	}

	public override bool IsMemoryWrite => true;
}
