// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// StoreObject
/// </summary>
public sealed class StoreObject : BaseIRInstruction
{
	public StoreObject()
		: base(3, 0)
	{
	}

	public override bool IsMemoryWrite => true;
}
