// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// Store64
/// </summary>
public sealed class Store64 : BaseIRInstruction
{
	public Store64()
		: base(3, 0)
	{
	}

	public override bool IsMemoryWrite => true;
}
