// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// StoreR4
/// </summary>
public sealed class StoreR4 : BaseIRInstruction
{
	public StoreR4()
		: base(3, 0)
	{
	}

	public override bool IsMemoryWrite => true;
}
