// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// Sub32
/// </summary>
public sealed class Sub32 : BaseIRInstruction
{
	public Sub32()
		: base(2, 1)
	{
	}
}
