// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// Throw
/// </summary>
public sealed class Throw : BaseIRInstruction
{
	public Throw()
		: base(1, 0)
	{
	}
}
