// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// ThrowIndexOutOfRange
/// </summary>
public sealed class ThrowIndexOutOfRange : BaseIRInstruction
{
	public ThrowIndexOutOfRange()
		: base(0, 0)
	{
	}
}
