// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// UnstableRegionStart
/// </summary>
public sealed class UnstableRegionStart : BaseIRInstruction
{
	public UnstableRegionStart()
		: base(0, 0)
	{
	}

	public override bool IgnoreDuringCodeGeneration => true;
}
