// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework.Core;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// Use
/// </summary>
public sealed class Use : BaseIRInstruction
{
	public Use()
		: base(0, 0)
	{
	}

	public override bool IgnoreDuringCodeGeneration => true;

	public override bool HasVariableOperands => true;
}
